<div class="container addtask">

	<div class="well bs-component">

		<form class="form-horizontal" role="form" action="index.php" validate method="POST">

			<fieldset>
				<legend>New task</legend>

				<div class="form-group">
					<label for="inputTask" class="col-lg-2 control-label">Name</label>
					<div class="col-lg-10">
						<input type="text" class="form-control" id="inputTask" name="inputTask"
							placeholder="my goal is .." required data-validation-required-message="Specify goal!">
					</div>
				</div>

				<div class="form-group">
					<label for="textNote" class="col-lg-2 control-label">Note</label>
					<div class="col-lg-10">
						<textarea class="form-control" rows="3" id="textNote" name="textNote"></textarea>
						<span class="help-block">A longer block of description text that breaks
							onto a new line and may extend beyond one line.</span>
					</div>
				</div>

				<div class="form-group">
					<div class="col-lg-10 col-lg-offset-2">
						<button type="button" class="btn btn-default" onclick="clearFRM();">Cancel</button>
						<button type="button" class="btn btn-primary" onclick="addAj(<?php echo $uid;?>);">Add</button>
					</div>
				</div>

			</fieldset>
		</form>

	</div>
</div>