 <hr class="footer-divider">  
 
			
  <div class="container">
 
      <!-- FOOTER -->
      <footer>
        
        <section class="copyright">
        	<div class="row">
							<div class="col-sm-3 col-md-3">
        <a class="logo" href="http://yarenty.com"><img alt="yarenty" src="images/yarenty.png" align="top" > &copy; 2015  yarenty.com</a>
  							</div>
							<div class="col-sm-6 col-md-6 text-center">
         <a href="about.php">About</a>
         &nbsp; <a href="faq.php">FAQ</a>
         &nbsp; <a href="contact.php">Contact</a></div>
     
         <div class="pull-right text-right col-sm-3 col-md-3"><a href="#">Back to top</a></div>
         </div>    
         </section>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- script src="https://code.jquery.com/jquery.js"></script -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/docs.min.js"></script>
<? if ($page == 'register' || $page =='profile') { ?>
	  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
  <script type="text/javascript" src="js/jquery.maphilight.min.js"></script>
  <script type="text/javascript" src="js/jquery.timezone-picker.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      // Set up the picker to update target timezone and country select lists.
      $('#timezone-image').timezonePicker({
        target: '#timezone',
        countryTarget: '#edit-site-default-country'
      });

      // Optionally an auto-detect button to trigger JavaScript geolocation.
      $('#timezone-detect').click(function() {
        $('#timezone-image').timezonePicker('detectLocation');
      });
    });
  </script>
<?    }	?>
    
    <?php echo printdebug();?>
    
    <script src="js/tasks.js"></script>
</body></html>