<hr/>
<a href="logout.php">xxx</a><br/>


	<!-- jQuery -->
		<script src="js/jquery.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="js/bootstrap.min.js"></script>

		<!-- Script to Activate the Carousel -->
		<script>
			$('.carousel').carousel({
				interval : 5000 //changes the speed
			})
		</script>
		
		<script>
		$('#on').click(function() {
			$('#on').toggleClass('active');
			$('#on').toggleClass('btn-success');
			$('#on').toggleClass('btn-default');

			$('#off').toggleClass('active');
			$('#off').toggleClass('btn-danger');
			$('#off').toggleClass('btn-default');
		});
		$('#off').click(function() {
			$('#on').toggleClass('active');
			$('#on').toggleClass('btn-success');
			$('#on').toggleClass('btn-default');

			$('#off').toggleClass('active');
			$('#off').toggleClass('btn-danger');
			$('#off').toggleClass('btn-default');
		});
	</script>


 <?php //echo printdebug();?>
	</body>

</html>

