      <div id="content_area">
        	<div class="message_container">
            	
            </div>
        	<div class="content_frame">
            	<div class="content_top"></div>
            	
                <div id="content_main">
                	<div class="content_main">
						<div class="componentheading"><?php if ($title != null) {
						echo $title;
						} else {
						echo "HOME";
						}?></div>

<table class="blog" cellpadding="0" cellspacing="0" width="100%">
<tbody><tr>
	<td valign="top">
					<div>
