<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="11th hour">
    <meta name="author" content="yarenty">

    <title>11th HOUR <?php 
    switch($page) {
		case 'login': echo '::LOGIN'; break;
		case 'register': echo '::REGISTER'; break;
		case 'about': echo '::ABOUT'; break;
		case 'contact': echo '::CONTACT'; break;
		case 'history': echo '::HISTORY'; break;
		case 'profile': echo '::PROFILE'; break;

	}    
    
    ?></title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
        
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    
    <!-- Custom styles for this template -->
    <link href="css/signin.css" rel="stylesheet">
    
    
    <!-- Custom styles for this template -->
    <link href="css/carousel.css" rel="stylesheet">
  	<style type="text/css"></style><style id="holderjs-style" type="text/css"></style>
  
    <link href="css/yaro.css" rel="stylesheet">
  	
  </head>



