			<div class="container">
			<div class="row">
				<div class="box">
					<div class="col-lg-3"></div>
					<div class="col-lg-6">
						<form>
							<hr>
							<h2 class="intro-text text-center">Find Bar Staff <strong>at the 11th Hour</strong></h2>
							<hr>
							<hr class="visible-xs">
							<h2 class="intro-text text-center">
								Don't Find Yourself Short-Staff
								Find available staff for your Bar right now!
							</h2>
							<div class="row">

								<div class="dropdown">
									<button class="btn btn-default dropdown-toggle btn-group-justified" type="button" id="dropdownMenu1" data-toggle="dropdown" style="text-align: -webkit-left;">
										What type of staff are you looking for?
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" style="width: 100%;">
										<li role="presentation">
											<a role="menuitem" tabindex="-1" href="#">Bartender</a>
										</li>
										<li role="presentation">
											<a role="menuitem" tabindex="-1" href="#">Floor Staff</a>
										</li>
										<li role="presentation">
											<a role="menuitem" tabindex="-1" href="#">Back Bar</a>
										</li>
										<li role="presentation">
											<a role="menuitem" tabindex="-1" href="#">Mixologist</a>
										</li>
									</ul>
								</div>
							</div>
							<br>
							<div class="row">
								<h2 class="intro-text">
									What day do you need the staff?
								</h2>
								<input type="date" class="form-control" placeholder="What day do you need the staff">
							</div>
							<br>
							<div class="row">
								<h2 class="intro-text">
									What Time do you need the staff?
								</h2>
								<input type="time" class="form-control" placeholder="What time do you need the staff">
								<br>
								<a type="button" class="btn btn-success btn-group-justified" href="results.html">
									Search!
								</a>
							</div>
					</div>
				</div>
			</div>
		</div>
