 <!-- Marketing messaging and featurettes-->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-5">
        	<center>
            <img class="img-circle"  alt="cool" src="images/cool.png" style="width: 140px; height: 140px;">

          		
          	<h2>Last minute</h2>
          <p>
          Read about our APP
          

          </p>
          <p><a class="btn btn-default" href="iosapp.php" role="button">View details </a></p>
          </center>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-5">
        	<center>
          <img class="img-circle" alt="productive" src="images/productivity.jpg" style="width: 140px; height: 140px;">
          <h2>Productive</h2>
          <p>
          Before start your day - plan it.<br/>
          Remember:<br/>
          <b><i>Failing to plan is planning to fail!</i></b>
		 </p>
          <p><a class="btn btn-default" href="register.pgp" role="button">Register </a></p>
        </div><!-- /.col-lg-4 -->

       </center>
        </div><!-- /.row -->
   
   </div>
        