	<div class="container">
		<div class="row">
			<div class="box">
				<div class="col-lg-12">
					<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
						<h3>Sam Malone</h3>
						<div class="row">
							<div class="col-md-3 col-lg-3 " align="center">
								<img alt="User Pic" src="http://ksr.wpengine.netdna-cdn.com/wp-content/uploads/2013/12/rc-sam-malone.jpg" class="img-circle" Style=" height:100px;
								width:100px;">

								<b>Availabile</b>
								<div class="btn-group btn-toggle">
									<button class="btn btn-default active" id="on">
										ON
									</button>
									<button class="btn btn-danger" id="off">
										OFF
									</button>
								</div>
							</div>

							<!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
							<dl>
							<dt>DEPARTMENT:</dt>
							<dd>Administrator</dd>
							<dt>HIRE DATE</dt>
							<dd>11/12/2013</dd>
							<dt>DATE OF BIRTH</dt>
							<dd>11/12/2013</dd>
							<dt>GENDER</dt>
							<dd>Male</dd>
							</dl>
							</div>-->
							<div class=" col-md-9 col-lg-9 ">
								<td>I have 5 years experince wokring in busy city centre bars.<br/>
								I can serve food and am quick on my feet<br/></td>
								<table class="table table-user-information">
									<tbody>
										<tr>
											<td>Years Experience</td>
											<td>5</td>
										</tr>
										<tr>
											<td>Your Skills</td>

											<td>Bartender, Floor Staff</td>
										</tr>
									</tbody>
								</table>
								<span class="pull-right"> <a href="index.php" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a> </span>

							</div>
							
							
							<div class="xxx" style="display:hidden;">
							
							<hr>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
		