<!-- NAVBAR -->
<body>

		<a class="brand" href="index.html" style="focus: 
    background-color: #FFFFFF;
    color: #FFFFFF;" ><img src="img/logo.png" style="width: 500px; height: 200px"></img>
		</a>
	
			<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
					<a class="navbar-brand" href="index.html">Business Casual <span class="badge" id="badge"><?php echo $badge;?></span></a>

				</div>
				
					</div>
<?php
if (! isset ( $_SESSION ["user"] )) {
	
	debug ( "user not in the session<br/>" );
	// not logged - default for all!
	
	?>  				
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav" style="padding: 0px">
						<li style="padding: 0px">
							<a href="iosapp.php" style="padding-top: 25px">I am Looking for Staff</a>
						</li>
						<li style="padding: 0px">
							<a href="register.php" style="padding-top: 25px">I am Looking for Work</a>
						</li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->

<?php
} else {
	debug ( "user in the session<br/>" );
	debug ( print_r ( $_SESSION ["user"], true ) );
	$user = $_SESSION ["user"];
	// logged
	?>  
	
						<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav" style="padding: 0px">
						<li style="padding: 0px">
							<a href="iosapp.php" style="padding-top: 25px">I am Looking for Staff</a>
						</li>
						<li style="padding: 0px">
							<a href="register.php" style="padding-top: 25px">I am Looking for Work</a>
						</li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->		
<? } ?>				
			</div>
			<!-- /.container -->
		</nav>
		
	