<h1>Debunking the Myth of the 10,000-Hours Rule: What It Actually Takes to Reach Genius-Level Excellence</h1>
by Maria Popova
<br/>

<h1>
How top-down attention, feedback loops, and daydreaming play into the science of success.
</h1>

<p>
The question of what it takes to excel — to reach genius-level acumen at a chosen endeavor — has occupied psychologists for decades and philosophers for centuries. Groundbreaking research has pointed to “grit” as a better predictor of success than IQ, while psychologists have admonished against the dangers of slipping into autopilot in the quest for skill improvement. In recent years, one of the most persistent pop-psychology claims has been the myth of the “10,000-hour rule” — the idea that this is the amount of time one must invest in practice in order to reach meaningful success in any field. But in Focus: The Hidden Driver of Excellence (public library), celebrated psychologist and journalist Daniel Goleman, best-known for his influential 1995 book Emotional Intelligence, debunks the 10,000-hour mythology to reveal the more complex truth beneath the popular rule of thumb:
</p>
<div class="alert alert-warning">
The “10,000-hour rule” — that this level of practice holds the secret to great success in any field — has become sacrosanct gospel, echoed on websites and recited as litany in high-performance workshops. The problem: it’s only half true. If you are a duffer at golf, say, and make the same mistakes every time you try a certain swing or putt, 10,000 hours of practicing that error will not improve your game. You’ll still be a duffer, albeit an older one.
<br/>
No less an expert than Anders Ericsson, the Florida State University psychologist whose research on expertise spawned the 10,000-hour rule of thumb, told me, “You don’t get benefits from mechanical repetition, but by adjusting your execution over and over to get closer to your goal.”
<br/>
“You have to tweak the system by pushing,” he adds, “allowing for more errors at first as you increase your limits.”
</div>

<p>
The secret to continued improvement, it turns out, isn’t the amount of time invested but the quality of that time. It sounds simple and obvious enough, and yet so much of both our formal education and the informal ways in which we go about pursuing success in skill-based fields is built around the premise of sheer time investment. Instead, the factor Ericsson and other psychologists have identified as the main predictor of success is deliberate practice — persistent training to which you give your full concentration rather than just your time, often guided by a skilled expert, coach, or mentor. It’s a qualitative difference in how you pay attention, not a quantitative measure of clocking in the hours. Goleman writes:
</p>

<div class="alert alert-info">
Hours and hours of practice are necessary for great performance, but not sufficient. How experts in any domain pay attention while practicing makes a crucial difference. For instance, in his much-cited study of violinists — the one that showed the top tier had practiced more than 10,000 hours — Ericsson found the experts did so with full concentration on improving a particular aspect of their performance that a master teacher identified.
</div>

<p>
Goleman identifies a second necessary element: a feedback loop that allows you to spot errors as they occur and correct them, much like ballet dancers use mirrors during practice. He writes:
</p>

<div class="alert alert-warning">
Ideally that feedback comes from someone with an expert eye and so every world-class sports champion has a coach. If you practice without such feedback, you don’t get to the top ranks.
<br/>
The feedback matters and the concentration does, too — not just the hours.
</div>

<p>
Additionally, the optimal kind of attention requires top-down focus. While daydreaming may have its creative benefits, in the context of deliberate practice it only dilutes the efficiency of the process. Goleman writes:
</p>

<div class="alert alert-error">
Daydreaming defeats practice; those of us who browse TV while working out will never reach the top ranks. Paying full attention seems to boost the mind’s processing speed, strengthen synaptic connections, and expand or create neural networks for what we are practicing.
<br/>
At least at first. But as you master how to execute the new routine, repeated practice transfers control of that skill from the top-down system for intentional focus to bottom-up circuits that eventually make its execution effortless. At that point you don’t need to think about it — you can do the routine well enough on automatic.
</div>

<p>
But this is where the amateurs and the experts diverge — too much automation, and you hit the “OK plateau,” ceasing to grow and stalling at proficiency level. If you’re going for genius, you need to continually shift away from autopilot and back into active, corrective attention:
</p>

<div class="alert alert-warning">
Amateurs are content at some point to let their efforts become bottom-up operations. After about fifty hours of training — whether in skiing or driving — people get to that “good-enough” performance level, where they can go through the motions more or less effortlessly. They no longer feel the need for concentrated practice, but are content to coast on what they’ve learned. No matter how much more they practice in this bottom-up mode, their improvement will be negligible.
<br/>
The experts, in contrast, keep paying attention top-down, intentionally counteracting the brain’s urge to automatize routines. They concentrate actively on those moves they have yet to perfect, on correcting what’s not working in their game, and on refining their mental models of how to play the game, or focusing on the particulars of feedback from a seasoned coach. Those at the top never stop learning: if at any point they start coasting and stop such smart practice, too much of their game becomes bottom-up and their skills plateau.
</div>

<p>
But even with the question of quality resolved, there’s still that of quantity: Just how much “deliberate practice” is enough? Focused attention, like willpower, is like a muscle and gets fatigued with exertion:
</p>

<div class="alert alert-info">
Ericsson finds world-class champions — whether weight-lifters, pianists, or a dog-sled team — tend to limit arduous practice to about four hours a day. Rest and restoring physical and mental energy get built into the training regimen. They seek to push themselves and their bodies to the max, but not so much that their focus gets diminished in the practice session. Optimal practice maintains optimal concentration.
</div>
<p>
In the rest of Focus, Goleman goes on to explore how concepts like attention-chunking, emotional empathy, and system blindness influence the pursuit of excellence. Complement it with how grit predicts achievement and the science of the “winner effect.”
</p>
