<h1>5 THINGS YOU'RE DOING THAT SEEM PRODUCTIVE, BUT AREN'T</h1>

<h2>THESE HABITS ARE GOOD INTENTIONED, BUT COULD BE SABOTAGING YOUR PRODUCTIVITY.</h2>
BY VIVIAN GIANG
In our always on, always busy work culture, it always seems there’s never enough time to get everything done.

That's why at some point, most of us will find shortcuts to maximize our efficiency to get ahead. After all, if we all need to get to the same destination, you don’t want to be the one taking the long road. Unfortunately, sometimes we’ll adopt systems and strategies that don’t actually propel us forward the way we think they do.

Below are five seemingly productive things you’re probably doing that are actually doing more harm than good.

<h2>1. MEMORIZING YOUR TO-DO LIST.</h2>
If you’re the kind of person who thinks making a to-do list is a waste of time, your strategy might be what’s wasting your time. According to David Allen, renowned author of Getting Things Done you need to write things down or, more importantly, you just need to keep tasks out of your head.

Why? Because "your head's designed for making intuitive choices about stuff,” he explains in a video interview with Fast Company in 2008. “Not for remembering and reminding.”

When you have all of this information in your head, your psyche doesn’t know the difference between priorities and you’ll end up getting scattered or overcommitting to things. Instead, Allen says writing things down is the best way to tackle your tasks.

<h2>2. PUTTING THE MOST IMPORTANT TASK AT THE TOP OF YOUR TO-DO LIST.</h2>
Most people will put the most important thing at the top of their list, but this will actually make you not want to do it, especially if you’re a procrastinator.

John Perry writes about playing the procrastinator’s game in his famous 1996 confessional essay "Structured Procrastination,” which was later expanded into the book The Art of Procrastination.

The Stanford professor explains that the reason why most of us put very important tasks off is because we’re all perfectionists in a way. We imagine how amazing the finished product will turn out because we know we’re capable of high standards. But the bar has been set so high that we keep putting the task off until we eventually run out of time and scramble to finish.

DON’T PUT YOUR MOST IMPORTANT TASK UP TOP SO THAT IT LOOMS AND INTIMIDATES THE WORK ETHICS OUT OF YOU.
Instead, Perry says you need to move the very important task further down on your list to mentally trick yourself to not dread the specific task so deeply. You’re basically warming yourself up with other less important tasks before tackling your very important task. He writes:

“The trick is to pick the right sorts of projects for the top of the list. The ideal sorts of things have two characteristics, First, they seem to have clear deadlines (but really don't). Second, they seem awfully important (but really aren't).”

In other words, you don’t put your most important task up top so that it looms and intimidates the work ethics out of you.

<h2>3. RELYING ON A TASK-MANAGEMENT SOFTWARE.</h2>
It might actually be OK for you to use a task-management software if you’re not someone who has major issues with productivity outputs. But if you are a bona-fide procrastinator, “collecting” softwares can end up hurting your output levels, says Allen.

The reasoning is simple: Note-taking and archiving softwares allow you to collect notes that can either be from formatted text, a handwritten note, a voice memo, or even a photo you took. All of these collected notes can be sorted and filed away for later usage and that’s exactly the problem, says Allen. While writing tasks down means you see it as actionable steps, merely collecting information means all that stuff will go back into your head because you won’t know what to do with the information after you collect it.

If you use a task-management program, Allen advises to clear everything collected every 24 to 48 hours.

<h2>4. DELAYING MAKING DECISIONS.</h2>
In his book Getting Things Done, Allen says that “if it takes less than two minutes to do it, do it now.” Delaying decisions might make it easier on you at the moment, but it’ll also have a chance of blowing up later on down the road.

TRUST AND HONE YOUR INTUITION SO MUCH THAT YOU SHOULD BE ABLE TO MAKE ANY DECISION IN NINE SECONDS OR LESS.
Vivian Rosenthal, founder and CEO at Snaps tells Fast Company that making quick decisions is how she conquers her biggest roadblocks. In fact, Rosenthal believes you need to trust and hone your intuition so much that you should be able to make any decision in nine seconds or less.

When you put off a task, it loses its meaning and you end up spending more energy revisiting that task and figuring out the meaning, or priority, attached to it. Instead, you need to be able to quickly integrate information, make decisions, assign it to a system or person, and move on to the next thing.

<h2>4. SAYING “YES” TO EVERYTHING.</h2>
You might think that saying “yes” to everything makes you an easier person to work with, but doing so also makes you an unproductive person to work with. The truth is, we’re all busy people with too much on our plate.

Those who are focused and keep their eyes on the bottom-line will become the most successful. If you commit yourself to every little thing that comes your way, your path will be scrambled and you won’t get anywhere on time.

While saying “yes” is much easier than saying “no,” doing that latter will keep you focused and on track. There’s a good strategy to saying “no,” according to a study published in the Journal of Consumer Research, which split 120 students into two groups that started their answer differently when saying no to something. One group turned tasks down by saying “I can’t” while another group turned things down by saying “I don’t.”

The study found that the group who said “I don’t” were able to turn down tasks significantly more times than the group who said “I can’t.” The word choice has a lot to do with your sense of control, which sends a message to your brain and affects your behavior the next time around. If you say, “I can’t do that for you,” then you are reminding yourself that you have limits and saying “no” is something you’re forced to do. On the other hand, if you say “I don’t have time to do that for you,” you are telling your brain that you have full control of the situation and choosing not to do something because you’re empowered to do so.

<h2>5. THINKING YOU’RE CAPABLE OF MULTITASKING.</h2>
It doesn’t matter how many studies have been published telling us that our brains can’t do multiple things at the same time, we still multitask because it gives us a false sense of accomplishment.

But the truth is, human brains weren’t built to multitask. UCLA researchers found in a study that your brain is "dumbed down" when you multitask because you’re using a different part of it that “adversely affects how you learn.”

Instead, a good strategy to adopt is to perform tasks in sequences, called “set shifting,” which is the practice of switching consciously and completely from one task to the next instead of doing everything at once. This will allow you to use your brain at high capacity for each task, but you can only think of the task you’re currently working on.

If your productivity isn’t where you want it to be, know that you don’t have to be 
the most highly motivated, passionate, high-performer to get things done. Get smart with your time and work practice and you’ll find it easier to “get in the zone” and up your productivity game.